config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home", as: "pages_home"
  resources :events, only: [:index, :new, :create] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, :capacity, :address, :description, :category, :date, :photo, presence: true
  validate :event_date_cannot_be_in_the_past
  validates :category, inclusion: { in: %w[music sports poetry fitness],
                                    message: "%{value} is not valid" }

  def event_date_cannot_be_in_the_past
    errors.add(:date, "can't be in the past") if date.present? && date < Date.today
  end

  include PgSearch::Model
  pg_search_scope :search_by_name_and_address_and_category,
                  against: %i[name address category],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :events, through: :bookings
  has_one_attached :avatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name avatar])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def create
    @event = Event.find(params[:event_id])
    @booking = Booking.new(event: @event, user: current_user, confirmed: false)
    @booking.save
    redirect_to booking_path(@booking)
  end

  def show
    @booking = Booking.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :find_event, only: :show

  def index
    if params[:query].present?
      @events = Event.search_by_name_and_address_and_category(params[:query])
    else
      @events = Event.all
    end

    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { event: event })
      }
    end
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to events_path, notice: "Event was successfully created."
    else
      flash[:notice] = "Sorry, something went wrong!"
      render :new
    end
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :photo, :address, :category, :date, :description, :capacity, :lat, :lng)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @events = Event.where("date >= ?", Date.today).order(date: :asc).limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @user ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/bookings/index.html.erb
<div class="main-container">
  <h1 style="color: white; text-align: center;">My Events</h1>

  <div class="booking-cards">
    <div class="row">
      <% @bookings.each do |booking| %>
        <div class="col-12 col-lg-3">
            <div class="card box-shadow m-3 card-event" id = "booking">
              <% if booking.event.photo.attached? %>
                <%= cl_image_tag booking.event.photo.key, height: 220, width: 350, crop: :fill, class: "card-img-top", style: "object-fit: cover" %>
              <% else %>
                <img class="card-img-top" src="https://images.unsplash.com/photo-1591474200742-8e512e6f98f8? ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80" alt="Card image cap">
              <% end %>

              <div class="card-body">
                <h5 class="card-title"><%= booking.event.name.upcase %></h5>
                <p class="card-text"><%= booking.event.address.capitalize %></p>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div style="text-align: center;">
  <h1 style="font-size: 50px; padding-bottom: 30px;">Conratulations!</h1>
  <h2 style="color: white; padding-bottom: 30px;"><%= @booking.event.name.capitalize %> was booked successfully</h2>

  <p style="color: white; padding-bottom: 30px;">Confirmation number: <%= rand(1000..3550) %></p>

  <%= link_to "Your Booked Events", bookings_path, class: "btn btn-dark b-r-1" %>
</div>

app/views/events/_info_window.html.erb
<h2><%= event.name %></h2>
<p><%= event.address %></p>

app/views/events/index.html.erb
<!-- Search Bar -->

      <div class="searchbar">
        <%= form_tag events_path, class: "form-inline", method: :get do %>
        <div style="display:flex">
        <%= text_field_tag :query,
                           params[:query],
                           class: "form-control",
                           placeholder: "Find an event" %>
        <%= submit_tag "Search", class: "btn btn-primary tita" %>
        </div>
        <% end %>
      </div>




<div class="body" style="display: flex; overflow: auto;">

  <!-- All event cards -->

  <div class="flat-cards col-12 col-lg-7" style="height: 600px; width: 60%">
    <div class="row">
      <% @events.each do |event| %>
        <div class="col-md-5">
          <button id="card-button" type="button" class="btn" data-toggle="modal" data-target="#event<%= event.id %>">
            <div class="card box-shadow m-3 card-event" style="grid-auto-rows: auto;">
              <% if event.photo.attached? %>
                <%= cl_image_tag event.photo.key, height: 220, width: 350, crop: :fill, class: "card-img-top", style: "object-fit: cover" %>
              <% else %>
                <img class="card-img-top" src="https://images.unsplash.com/photo-1591474200742-8e512e6f98f8? ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80" alt="Card image cap">
              <% end %>

              <div class="card-body">
                <h5 class="card-title"><%= event.name.upcase %></h5>
                <p class="card-text"><%= event.address.capitalize %></p>
              </div>
            </div>
          </button>
        </div>
      <% end %>
    </div>
  </div>

  <!-- Map -->

   <div id="map"
       style="position: -webkit-sticky; position: sticky; top: 0; width: 40%"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>">
  </div>

</div>

<% @events.each do |event| %>
<!-- Modal -->
  <div class="modal fade" id="event<%= event.id %>" tabindex="-1" aria-labelledby="event<%= event.id %>Label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="my-header">
          <h5 class="modal-title" id="event<%= event.id %>Label"><%= event.name.upcase %></h5>
          <button type="button" class="btn-close btn-dark model-x" data-dismiss="modal" aria-label="Close">X</button>
        </div>
        <div class="modal-body">
         <!-- Content of the modal -->
          <% if event.photo.attached? %>
                <%= cl_image_tag event.photo.key, height: 220, width: 350, crop: :fill, class: "card-img-top", style: "object-fit: cover" %>
          <% else %>
                <img class="card-img-top" src="https://images.unsplash.com/photo-1591474200742-8e512e6f98f8? ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80" alt="Card image cap">
              <% end %>
          <p><%= event.date %></p>
          <p>Category: <%= event.category.capitalize %></p>
          <p>Description: <%= event.description.capitalize %></p>
          <p>Capacity: <%= event.capacity %></p>
          <p>Address: <%= event.address.capitalize %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-dark b-r" data-dismiss="modal">Save Event</button>
          <%= simple_form_for([event, Booking.new]) do |f| %>
            <%= f.submit "Book Event", class: "btn btn-dark b-r" %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/events/new.html.erb
<div class= "container pl-2 pb-5">
<h1><strong>Create your Event!</strong></h1>
</div>

<div class="container border border-light rounded-lg" style="background:white;">
  <%= simple_form_for(@event) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="p-3">
      <%= f.input :name, input_html: { class: "field" }, placeholder: "First Name and Last Name" %>
      <%= f.input :address, input_html: { class: "field" }, placeholder: "Street, City, State and Zip Code" %>
      <%= f.input :description, input_html: { class: "field" }, placeholder: "Write a short description of your event..." %>
      <%= f.input :date, as: :date, html5: true, input_html: { class: "field" } %>
      <%= f.input :category, :collection => %w(music sports poetry fitness), input_html: { class: "field" } %>
      <%= f.input :capacity, placeholder: "How many people are allowed? ", input_html: { class: "field" } %>
    </div>

     <%= f.input :photo, as: :file %>

    <div class="form-actions mb-5 p-3 rounded-sm btn">
      <%= f.button :submit, class: "btn btn-dark b-r-1" %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<h1 style="color: black"><%= @event.name %> was booked successfully</h1>

<p>Confirmation number: <%= rand(1000..3550) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hobbyist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/3929e16ef5.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>

    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload", defer: true %>
    <%= stylesheet_pack_tag "application" %>
  </head>

  <body class="<%= "home-body" if current_page?(pages_home_path) %>">
    <div id="container">
      <div id="main">
        <%= render "shared/navbar" %>
        <%= render "shared/flashes" %>


        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>

      <%= yield %>


    <div id="footer" class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
    <div class="footer-copyright">
      Hobbyist
    </div>
  </div>

  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="hero-image position-absolute"></div>

<div id="container">

  <div class="home-content" >
    <h1 class="text-center"><strong>Take your Hobby<br>anywhere!</strong></h1>
  </div>


   <!--  Search Bar -->

  <div class="container">
        <div class="search">
          <%= form_tag events_path, class: "form-inline", method: :get do %>
          <div style="display:flex">
          <%= text_field_tag :query,
                             params[:query],
                             class: "form-control",
                             placeholder: "Find an event" %>
          <%= submit_tag "Search", class: "btn btn-primary tita" %>
          </div>
          <% end %>
        </div>
  </div>

    <!--  -->

    <div class="flat-cards">
      <h1 style="text-align: center; pb: 10px;">Happening Soon</h1>
        <div class="row">
          <% @events.each do |event| %>
            <div>
              <button type="button" class="btn" data-toggle="modal" data-target="#event<%= event.id %>">
                <div class="card box-shadow card-event">
                  <% if event.photo.attached? %>
                    <%= cl_image_tag event.photo.key, height: 220, width: 350, crop: :fill, class: "card-img-top", style: "object-fit: cover" %>
                  <% else %>
                    <img class="card-img-top" src="https://images.unsplash.com/photo-1591474200742-8e512e6f98f8? ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80" alt="Card image cap">
                  <% end %>

                  <div class="card-body">
                    <h5 class="card-title"><%= event.name.upcase %></h5>
                    <p class="card-text"><%= event.description.capitalize %></p>
                    <!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#event<%= event.id %>"> -->
                  </div>
                </div>
              </button>
            </div>
          <% end %>
        </div>
    </div>

    <% @events.each do |event| %>
    <div class="modal fade" id="event<%= event.id %>" tabindex="-1" aria-labelledby="event<%= event.id %>Label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="my-header">
          <h5 class="modal-title" id="event<%= event.id %>Label"><%= event.name.upcase %></h5>
          <button type="button" class="btn-close btn-dark model-x" data-dismiss="modal" aria-label="Close">X</button>
        </div>
        <div class="modal-body">
         <!-- Content of the modal -->
          <% if event.photo.attached? %>
                <%= cl_image_tag event.photo.key, height: 220, width: 350, crop: :fill, class: "card-img-top", style: "object-fit: cover" %>
          <% else %>
                <img class="card-img-top" src="https://images.unsplash.com/photo-1591474200742-8e512e6f98f8? ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80" alt="Card image cap">
              <% end %>
          <p><%= event.date %></p>
          <p>Category: <%= event.category.capitalize %></p>
          <p>Description: <%= event.description.capitalize %></p>
          <p>Capacity: <%= event.capacity %></p>
          <p>Address: <%= event.address.capitalize %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-dark b-r" data-dismiss="modal">Save Event</button>
          <%= simple_form_for([event, Booking.new]) do |f| %>
            <%= f.submit "Book Event", class: "btn btn-dark b-r" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
 <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
 <%= link_to "Hobbyist", pages_home_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Events", events_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <button type="button" class="_1usxwsg6" aria-expanded="false" id="field-guide-toggle" data-testid="cypress-headernav-profile">
            <div aria-label="Main navigation menu">
              <svg viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="presentation" focusable="false" style="display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible;">
                <g fill="none" fill-rule="nonzero">
                    <path d="m2 16h28"></path>
                    <path d="m2 24h28"></path>
                    <path d="m2 8h28"></path>
                </g>
            </svg>
            </div>

            <% if user_signed_in? %>
              <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
            <% else %>
              <%= image_tag "https://cdn3.iconfinder.com/data/icons/vector-icons-6/96/256-512.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <% if user_signed_in? %>
                <%= current_user.first_name %>
                <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
                <%= link_to "Host an event", new_event_path, class: "dropdown-item" %>
                <%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                <% else %>
                  <a type="button" class="dropdown-item" data-toggle="modal" data-target="#SignupModal">
                    Sign up
                  </a>
                  <a type="button" class="dropdown-item" data-toggle="modal" data-target="#LoginModal">
                    Log in
                  </a>
                  <a type="button" class="dropdown-item" data-toggle="modal" data-target="#SignupModal">
                    Host an event
                  </a>
              <% end %>
            </div>
        </button>
      </li>
    </ul>
  </div>
</div>
<!-- Modal SignUp -->
<div class="modal fade" id="SignupModal" tabindex="-1" aria-labelledby="SignupModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="SignupModalLabel">Sign up</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :first_name,
                      required: true,
                      autofocus: true %>
          <%= f.input :last_name,
                      required: true,
                      autofocus: true %>
          <%= f.input :email,
                      required: true,
                      autofocus: true,
                      input_html: { autocomplete: "email" } %>
          <%= f.input :password,
                      required: true,
                      hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                      input_html: { autocomplete: "new-password" } %>
          <%= f.input :password_confirmation,
                      required: true,
                      input_html: { autocomplete: "new-password" } %>
        </div>

        <a type="button" class="link" data-toggle="modal" data-target="#LoginModal" data-dismiss="modal">
            Log in
        </a>
        <div>
          <% if devise_mapping.recoverable? && controller_name != "passwords" && controller_name != "registrations" %>
          <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.button :submit, "Sign up", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

<!-- login Modal -->
<div class="modal fade" id="LoginModal" tabindex="-1" aria-labelledby="LoginModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="LoginModalLabel">Log in</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="form-inputs">
            <%= f.input :email,
                        required: false,
                        autofocus: true,
                        input_html: { autocomplete: "email" } %>
            <%= f.input :password,
                        required: false,
                        input_html: { autocomplete: "current-password" } %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>

      <a type="button" class="link" data-toggle="modal" data-target="#SignupModal" data-dismiss="modal">
            Sign up
      </a>
      <div>
        <% if devise_mapping.recoverable? && controller_name != "passwords" && controller_name != "registrations" %>
        <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
        <% end %>
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.button :submit, "Log in", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
        <% end %>